# serverless.yml
service: es-cleanup-lambda

provider:
  name: aws
  environment:
    es_endpoint: ${file(./environment.${opt:stage, self:provider.stage}.yml):es_endpoint}
    index: all
    delete_after: "60"
    index_format: "%Y.%m.%d"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "es:*"
      Resource: ${file(./environment.${opt:stage, self:provider.stage}.yml):es_arn}


functions:
  es-cleanup-lambda:
    handler: es-cleanup.lambda_handler
    name: es-cleanup-lambda-${opt:stage, self:provider.stage}
    description: ES old index removal
    runtime: python2.7
    memorySize: "128"
    timeout: 300
    package:
      exclude:
        - ./**
      include:
        - es-cleanup.py
        - LICENSE.md
        - README.md
        - CONTRIBUTING.md
    events:
      # Invoke Lambda function every night at 01.00 AM
      - schedule: cron(0 1 * * ? *)

resources:
  Description: "AWS Lambda: Elasticsearch Index Cleanup"
